from __future__ import annotations

import os
from pathlib import Path
from tempfile import gettempdir

from PySide6.QtCore import QUrl, QObject, Signal, Qt
from PySide6.QtNetwork import QNetworkCookie
from PySide6.QtWidgets import QVBoxLayout, QHBoxLayout, QLabel
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage

from qfluentwidgets import MessageBoxBase, SubtitleLabel, BodyLabel, PrimaryPushButton, PushButton

from ui.i18n import t


class CookieCollector(QObject):
    """Listens to a QWebEngineCookieStore and aggregates all cookies."""

    def __init__(self, profile: QWebEngineProfile, parent: QObject = None) -> None:
        super().__init__(parent)
        self._store = profile.cookieStore()
        # Dictionary mapping (domain, name, path) to QNetworkCookie to ensure we keep the latest
        self._cookies: dict[tuple[str, str, str], QNetworkCookie] = {}
        
        # Connect signal
        self._store.cookieAdded.connect(self._on_cookie_added)
        
        # Force a load of all existing cookies from disk/memory into our dict
        self._store.loadAllCookies()

    def _on_cookie_added(self, cookie: QNetworkCookie) -> None:
        domain = cookie.domain()
        name = cookie.name().data().decode("utf-8")
        path = cookie.path()
        self._cookies[(domain, name, path)] = QNetworkCookie(cookie)

    def write_netscape_format(self, output_path: str) -> None:
        """Export all collected cookies to a Netscape HTTP Cookie File format."""
        lines = [
            "# Netscape HTTP Cookie File",
            "# This file was generated by YTSpot Downloader",
            "# https://curl.haxx.se/rfc/cookie_spec.html",
            "# This is a generated file!  Do not edit.",
            ""
        ]

        for cookie in self._cookies.values():
            domain = cookie.domain()
            # If domain begins with a dot, it covers subdomains
            subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.path()
            secure = "TRUE" if cookie.isSecure() else "FALSE"
            
            if cookie.isSessionCookie():
                expires = 0
            else:
                expires = int(cookie.expirationDate().toSecsSinceEpoch())

            name = cookie.name().data().decode("utf-8")
            value = cookie.value().data().decode("utf-8")

            lines.append(f"{domain}\t{subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")


class BotBypassWindow(MessageBoxBase):
    """
    A custom MessageBox that integrates a basic web browser.
    Allows the user to manually solve captchas or age gates, then saves
    the authenticated session's cookies so yt-dlp can use them.
    """
    
    # Emitted with the path to the written cookies file when successful
    cookies_extracted = Signal(str)

    def __init__(self, target_url: str, error_detail: str, parent=None):
        super().__init__(parent)
        self.setWindowTitle(t("bot_bypass_title"))
        
        self.viewLayout.setSpacing(10)
        
        # Create Title
        from qfluentwidgets import SubtitleLabel
        self.titleLabel = SubtitleLabel(t("bot_bypass_title"), self)
        self.viewLayout.addWidget(self.titleLabel)
        
        # Instructions
        full_text = f"<b>{error_detail}</b><br><br>{t('bot_bypass_instructions')}"
        self._desc = BodyLabel(full_text)
        self._desc.setWordWrap(True)
        self.viewLayout.addWidget(self._desc)
        
        # Use the global default profile so cache and Cloudflare clearance persists!
        # This makes the browser blisteringly fast on repeat opens.
        self._profile = QWebEngineProfile.defaultProfile()
        
        settings = self._profile.settings()
        settings.setAttribute(settings.WebAttribute.JavascriptEnabled, True)
        settings.setAttribute(settings.WebAttribute.PluginsEnabled, True)
        settings.setAttribute(settings.WebAttribute.LocalStorageEnabled, True)
        settings.setAttribute(settings.WebAttribute.WebGLEnabled, True)
        settings.setAttribute(settings.WebAttribute.Accelerated2dCanvasEnabled, True)
        
        self._page = QWebEnginePage(self._profile, self)
        
        self._browser = QWebEngineView(self)
        self._browser.setPage(self._page)
        
        # Force a minimum size so it's a usable browser window
        self._browser.setMinimumSize(800, 600)
        self.viewLayout.addWidget(self._browser)
        
        # Attach our cookie listener
        self._cookie_collector = CookieCollector(self._profile, self)
        
        # Navigate
        self._browser.setUrl(QUrl(target_url))
        
        # Tweak the standard MessageBoxBase buttons
        self.yesButton.setText(t("bot_bypass_save"))
        self.cancelButton.setText(t("cancel"))
        
        # Override the yesButton clicked behavior to export cookies before closing
        self.yesButton.clicked.disconnect()
        self.yesButton.clicked.connect(self._on_save_clicked)

    def _on_save_clicked(self) -> None:
        """User states they have successfully bypassed the checks."""
        self.yesButton.setEnabled(False)
        self.cancelButton.setEnabled(False)
        
        cookie_file = os.path.join(gettempdir(), "ytspot_bypass_cookies.txt")
        html_file = os.path.join(gettempdir(), "ytspot_bypass_html.html")
        url_file = os.path.join(gettempdir(), "ytspot_bypass_url.txt")
        
        try:
            self._cookie_collector.write_netscape_format(cookie_file)
        except Exception as exc:
            from qfluentwidgets import InfoBar, InfoBarPosition
            InfoBar.error(
                title="Cookie Extraction Failed",
                content=str(exc),
                orient=Qt.Horizontal,
                isClosable=True,
                position=InfoBarPosition.TOP,
                duration=4000,
                parent=self
            )
            self.yesButton.setEnabled(True)
            self.cancelButton.setEnabled(True)
            return

        def _on_html(html_data: str) -> None:
            try:
                with open(html_file, 'w', encoding='utf-8') as f:
                    f.write(html_data)
                
                # Write the *exact* target URL this HTML matches so the
                # background scraper knows it can safely consume it.
                current_url = self._browser.url().toString()
                with open(url_file, 'w', encoding='utf-8') as f:
                    f.write(current_url)

                self.cookies_extracted.emit(cookie_file)
                self.accept()
            except Exception as e:
                print(f"[BotBypass] HTML dump failed: {e}")
                self.accept()

        self._page.toHtml(_on_html)

    def closeEvent(self, event) -> None:
        """Cleanly destroy WebEngine resources so Qt doesn't spew warnings."""
        if hasattr(self, '_browser'):
            self._browser.setPage(None)
        if hasattr(self, '_page'):
            self._page.deleteLater()
        super().closeEvent(event)
