"""
core/cookie_wizard.py  –  Playwright-based cookie capture wizard
================================================================
Opens a headed Chromium browser so the user can log in to a site,
then captures and saves the session cookies in Netscape format.

Zero GUI imports — pure Python + Playwright.
Any UI dialogs (instructions, success/failure messages) must be shown
by the caller (e.g. ui/app_window.py) before and after this function.
"""

from __future__ import annotations

import logging
from pathlib import Path

from utils.paths import get_app_cookies_path
from utils.playwright_check import (
    PlaywrightNotAvailable,
    require_playwright_or_raise,
)

logger = logging.getLogger(__name__)


def format_netscape_cookies(cookies: list) -> str:
    """Convert a Playwright cookies list to Netscape-format string."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by YTSpot Downloader",
        "",
    ]
    for c in cookies:
        domain      = c["domain"]
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path        = c["path"]
        secure      = "TRUE" if c["secure"] else "FALSE"
        expiry      = int(c.get("expires", 0))
        if expiry == -1:
            expiry = 0
        lines.append(
            f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{c['name']}\t{c['value']}"
        )
    return "\n".join(lines)


def run_cookie_wizard(start_url: str = "https://www.youtube.com") -> bool:
    """
    Launch a headed Chromium browser for the user to log in.

    After the user closes the browser, captures all cookies and saves them
    to the standard app cookies path (~/.ytspot/app_cookies.txt on Unix,
    %APPDATA%\\.ytspot\\app_cookies.txt on Windows).

    Parameters
    ----------
    start_url :
        URL to navigate to on launch.  Falls back to YouTube home if it
        is not an HTTP(S) address (e.g. a yt-dlp ``ytsearch:`` string).

    Returns
    -------
    True  – cookies saved successfully.
    False – browser closed with no cookies, or an error occurred.

    Raises
    ------
    PlaywrightNotAvailable
        When Playwright Chromium is not installed. The caller should
        show a clear MessageBox using ``exc.message_en`` / ``message_he``
        instead of crashing.
    """
    require_playwright_or_raise("Sign-in / Cookie wizard")
    from playwright.sync_api import sync_playwright

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=False)
            context = browser.new_context()
            page    = context.new_page()

            target = start_url if start_url.startswith("http") else "https://www.youtube.com"
            page.goto(target, wait_until="load")

            browser_closed = [False]

            def _on_close(*_args: object) -> None:
                browser_closed[0] = True

            page.on("close", _on_close)

            while not browser_closed[0]:
                try:
                    page.wait_for_timeout(1000)
                except Exception:
                    break

            cookies = context.cookies()
            if not cookies:
                logger.warning("[CookieWizard] Browser closed with no cookies captured.")
                return False

            netscape_str = format_netscape_cookies(cookies)
            cookie_path: Path = get_app_cookies_path()
            cookie_path.parent.mkdir(parents=True, exist_ok=True)
            cookie_path.write_text(netscape_str, encoding="utf-8")

            logger.info("[CookieWizard] Saved %d cookies to %s", len(cookies), cookie_path)
            return True

    except Exception as exc:
        logger.error("[CookieWizard] Failed: %s", exc)
        return False
