import os
import logging
from pathlib import Path
from playwright.sync_api import sync_playwright

logger = logging.getLogger(__name__)

def _get_app_cookies_path() -> Path:
    if os.name == "nt":
        base = Path(os.environ.get("APPDATA", Path.home()))
    else:
        base = Path.home()
    return base / ".ytspot" / "app_cookies.txt"

def format_netscape_cookies(cookies: list) -> str:
    """Convert Playwright cookies list to Netscape format string."""
    lines = ["# Netscape HTTP Cookie File", "# This file is generated by YTSpot Downloader", ""]
    for c in cookies:
        domain = c['domain']
        # Netscape format requires a leading dot for domain-wide cookies
        include_sub = "TRUE" if domain.startswith('.') else "FALSE"
        path = c['path']
        secure = "TRUE" if c['secure'] else "FALSE"
        # Expiry is a unix timestamp or 0
        expiry = int(c.get('expires', 0))
        if expiry == -1: expiry = 0
        
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{c['name']}\t{c['value']}")
    return "\n".join(lines)

def run_cookie_wizard(parent_window=None, start_url: str = "https://www.youtube.com") -> bool:
    """
    Opens a headed browser for the user to log in to a specific site.
    Saves cookies to app_cookies.txt and returns True on success.
    """
    try:
        from PySide6.QtWidgets import QMessageBox
        
        # 1. Inform the user
        info_msg = (
            "כעת ייפתח חלון דפדפן.\n\n"
            f"1. התחבר לחשבון שלך באתר: {start_url}\n"
            "2. לאחר שתסיים להתחבר ותראה את עמוד הבית (או את הפרופיל שלך), פשוט סגור את חלון הדפדפן.\n\n"
            "התוכנה תשמור את פרטי ההתחברות באופן אוטומטי ותשתמש בהם להורדות."
        )
        QMessageBox.information(parent_window, "אשף התחברות לאתרים", info_msg)

        with sync_playwright() as p:
            # We use headed mode so the user can interact
            browser = p.chromium.launch(headless=False)
            context = browser.new_context()
            page = context.new_page()

            # Ensure the URL is a valid HTTP(S) link. 
            # If it's a 'ytsearch:' command, default to YouTube home
            target = start_url if start_url.startswith("http") else "https://www.youtube.com"
            
            # Go to the starting URL
            page.goto(target, wait_until="load")
            
            # Keep it open until the browser is closed by the user
            # We wait for the 'close' event
            browser_closed = [False]
            def on_close(*args): browser_closed[0] = True
            page.on("close", on_close)
            
            while not browser_closed[0]:
                try:
                    # Check if user is logged in (Avatar button exists)
                    # We don't force closure, we let the user close it when ready.
                    page.wait_for_timeout(1000)
                except:
                    break

            # Capture cookies before final exit
            cookies = context.cookies()
            if cookies:
                netscape_str = format_netscape_cookies(cookies)
                cookie_path = _get_app_cookies_path()
                cookie_path.parent.mkdir(parents=True, exist_ok=True)
                cookie_path.write_text(netscape_str, encoding="utf-8")
                
                logger.info(f"Successfully saved {len(cookies)} cookies to {cookie_path}")
                return True
            
            return False

    except Exception as e:
        logger.error(f"Cookie Wizard failed: {e}")
        return False
        