"""Write packaging/version_info.txt for PyInstaller's --version-file flag.

PyInstaller embeds a Windows VS_VERSIONINFO resource into the produced
EXE when you pass ``--version-file``. The expected format is a Python
literal (a single ``VSVersionInfo(...)`` call), not Microsoft's .rc
syntax. Generating it from ``version.py`` keeps the EXE metadata
(ProductVersion, FileVersion, CompanyName, FileDescription, …) in
exact sync with the rest of the app — bumping the version in one place
propagates everywhere.

Run this script from the build script before invoking PyInstaller.
Do not commit the generated ``version_info.txt`` — it is reproduced
deterministically on every build.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add repo root to sys.path so this script runs both from the
# packaging/ folder and from the repo root.
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

from version import (  # noqa: E402
    __version__,
    VERSION_INFO,
    PRODUCT_NAME,
    COMPANY_NAME,
    COPYRIGHT,
)

OUT = HERE / "version_info.txt"

# VS_VERSIONINFO requires a 4-tuple; pad with a trailing 0 (build #).
FILEVERSION = (*VERSION_INFO, 0)
PRODUCTVERSION = FILEVERSION

# Internal name and original filename should be the EXE name.
INTERNAL_NAME = "ytspot"
ORIGINAL_FILENAME = "ytspot.exe"

# Short product description used by Windows Explorer's tooltip.
FILE_DESCRIPTION = f"{PRODUCT_NAME} — YouTube / YouTube Music / Spotify downloader"

TEMPLATE = """# Auto-generated by packaging/generate_version_info.py — DO NOT EDIT.
# Bump ``version.__version__`` and re-run the build script to update.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={prodvers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', {company!r}),
            StringStruct('FileDescription', {file_desc!r}),
            StringStruct('FileVersion', {file_ver!r}),
            StringStruct('InternalName', {internal!r}),
            StringStruct('LegalCopyright', {copyright!r}),
            StringStruct('OriginalFilename', {orig!r}),
            StringStruct('ProductName', {product!r}),
            StringStruct('ProductVersion', {prod_ver!r}),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def build(out_path: Path = OUT) -> Path:
    body = TEMPLATE.format(
        filevers=FILEVERSION,
        prodvers=PRODUCTVERSION,
        company=COMPANY_NAME,
        file_desc=FILE_DESCRIPTION,
        file_ver=__version__,
        internal=INTERNAL_NAME,
        copyright=COPYRIGHT,
        orig=ORIGINAL_FILENAME,
        product=PRODUCT_NAME,
        prod_ver=__version__,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body, encoding="utf-8", newline="\n")
    return out_path


if __name__ == "__main__":
    p = build()
    print(f"Wrote {p}  (version={__version__}, product={PRODUCT_NAME})")
